### ISSUE TITLE
(Т) Неправильная работа метода Car.ChangeOwner

### ISSUE THREAD

**Issue by ikit-mita** [olegBryukhanov/HomeWork2#3]
По твоей логике выходит, что даже если у водителя нету нужной категории, то все равно он будет прописан в паспорте машины, и номер машине выставится

**Comment by olegBryukhanov** [comment]
Исправил.

**Comment by ikit-mita** [comment]
можно было перенести driver.OwnCar(this); на первую строчку метода ChangeOwner и все заработало бы как надо. Но и твой вариант подходит
